### ISSUE TITLE
Including and excluding files and/or folders

### ISSUE THREAD

**Issue by dstallenberg** [bvobart/mllint#15]
### Who

*The developer*

As a developer I want to be able to configure mllint instead of the underlying linters.

### What

Currently, by default the mllint tool includes all files/folders, even virtual environments.
To exclude the virtual environment you have to create a configuration setting for each specific linter.

### Why

This is an issue since as a developer I want to use mllint without thinking about the underlying linters.

## Feature

It would be nice if for at least some settings we can simply configure mllint instead of the underlying linters. 
One such setting would be including and excluding project files.

**Comment by bvobart** [comment]
Hi Dimitri, thanks for your issue! Indeed `mllint` expects / encourages you to configure your code quality linters properly with your custom rules for file exclusion and which rules to enable / disable, parameters for those rules, etc. `mllint` simply executes the linters and lets them pick up on the linter configuration that you have in your project. This way, if you were to run that linter by itself (e.g. in your IDE) instead of through `mllint`, then it will still give you the same results.

That said, I'm all for sensible defaults; `mllint` should not include virtual environments in its analysis, you're absolutely right in that. iirc, `mllint` already instructs the CQ linters to ignore the `.venv` folder if they don't already do so themselves. That doesn't always happen for `venv` folders though, so I'll need to fix that. Similarly, the function that counts number of Python files (which is also used for total number of lines of code) currently only ignores hidden folders (starting with a dot), which includes `.venv`, but not `venv`.

Which version of `mllint` are you currently using (run `mllint version`)? And which specific linters were not ignoring your virtualenvs? Also, is your virtualenv folder called `venv` or `.venv`?

**Comment by dstallenberg** [comment]
Hi, thanks for your quick response!
Our virtualenv is indeed called `venv` (automatically generated by pycharm ide).
We use mllint version `0.9.0`.
We only had issues with pylint.

**Comment by bvobart** [comment]
Alright, thanks for the info, I've fixed this in v0.9.1, which I've just released: https://github.com/bvobart/mllint/releases/tag/v0.9.1

CI takes about 10-15 minutes until it's released to PyPI, you can keep track of progress [here](https://github.com/bvobart/mllint/actions/runs/902792342) if you like (or try updating `mllint` in more than 15 minutes of course :P).
