### ISSUE TITLE
Formatting not working on Powershell

### ISSUE THREAD

**Issue by ami232** [bvobart/mllint#23]
I'm working on Windows.
Formatting is not working properly on Powershell.
Is Powershell supported?

This is what mllint looks like on Powershell.
![image](https://user-images.githubusercontent.com/16015401/124905009-df317f80-dfe5-11eb-84d6-ffe3c9ea928d.png)

For comparison, this is what mllint looks like on git bash on the same computer (everything OK).
![image](https://user-images.githubusercontent.com/16015401/124905276-2ddf1980-dfe6-11eb-8912-4e102b37f42b.png)

**Comment by bvobart** [comment]
Hi, thanks for the issue :) I don't test `mllint` on Powershell so I didn't notice this yet. Windows is supported, though I cannot guarantee that formatting will be correct for every shell. I personally use the `fish` shell on Manjaro Linux and `zsh` within WSL2 on Windows. I haven't tried Powershell or Git Bash yet, but it's good to see that Git Bash works fine :)

As for Powershell (and by extension probably also cmd.exe), it seems like it primarily has difficulty printing bold text. Strangely enough, the first two lines (before the first `---`) do seem to be coloured correctly. Unfortunately, there's not much I can do about it as the problem lies in the library I'm using for coloured output, this issue on their Github seems to be most related: https://github.com/fatih/color/issues/32

So yeah best advice I can give is don't use Powershell. As a workaround, either run `mllint` in Git Bash as you already did, or in basically any Linux / Unix shell under WSL2. Maybe using Powershell within Windows Terminal can help fix these issues too, or perhaps try [Powershell Core](https://github.com/PowerShell/PowerShell).

<sub><sup>Sorry for the late response btw, I was on vacation for two weeks</sup></sub>
